### ISSUE TITLE
Readability issue

### ISSUE THREAD

**Issue by Ghost---Shadow** [rxaviers/async-pool#16]
https://github.com/rxaviers/async-pool/blob/master/lib/es7.js#L20

I was scratching my head on this line

```js
    const e = p.then(() => executing.splice(executing.indexOf(e), 1));
```

Then I realized that this is equivalent to this

```js
    const e = p.then((x) => executing.splice(executing.indexOf(x), 1));
```

I know js has a lot of weird rules but, for readability reasons can we avoid these?

This would be a big help for dumb people like me :)

**Comment by pmstss** [comment]
It's not an equivalent. We want to remove promise `e` itself from array of `executing` (and not an resolved result of `p`).

**Comment by rxaviers** [comment]
Correct. Closing this as non-issue
