### ISSUE TITLE
Typescript bindings

### ISSUE THREAD

**Issue by IlyaSemenov** [rxaviers/async-pool#20]
Currently the package is missing typescript bindings, so the result of running `asyncPool` is untyped. Can you please incorporate typings?

I'm using this as a workaround:

```ts
declare module "tiny-async-pool" {
	export default function<P, V>(
		poolSize: number,
		parameters: P[],
		worker: (p: P) => Promise<V>,
	): Promise<V[]>
}
```

You can simply put `export default ...` (without the wrapping `declare module`) in `index.d.ts` in the root of your package, that should do it.

**Comment by nojvek** [comment]
Should perhaps create a PR for this

**Comment by bespokebob** [comment]
You can just use the bindings from DefinitelyTyped: `@types/tiny-async-pool`

**Comment by rxaviers** [comment]
Please, is this still needed? Or does https://github.com/rxaviers/async-pool/issues/20#issuecomment-632869464 solve it for general usage?

**Comment by rxaviers** [comment]
Will reopen if there's still desire for this, in which case PR is welcome. I can add it since API is stable and therefore such definition might have little maintenance. Thanks
