### ISSUE TITLE
another args to function

### ISSUE THREAD

**Issue by SIMBaIrk** [rxaviers/async-pool#24]
in ES6 can use ...theArgs for function

`async function asyncPool(poolLimit, array, iteratorFn, ...theArgs) {`
...
`const p = Promise.resolve().then(() => iteratorFn(item, array, theArgs));`

in work i use that:

```
async function ticker(item, array, userId){
  return new Promise(base.findOne({'userId': userId, 'field': item}));
}
```

**Comment by rxaviers** [comment]
Sorry for the delay here.. Sure thing, PR welcome. Thanks

**Comment by rxaviers** [comment]
Sorry for the delay here.. Revisiting your request, it seems what you need can be accomplished independently of the proposed `asyncPool` API change. User code can pass `theArgs` to the `iteratorFn`. I am happy to reopen if you demonstrate a use case where API change is mandatory. Thanks
