### ISSUE TITLE
Failed to process the request

### ISSUE THREAD

**Issue by jiangtao-zzz** [rxaviers/async-pool#25]
Excuse me, how can I retry a request if it fails and maintain the number of concurrent requests

**Comment by rxaviers** [comment]
Please, what have you tried?

**Comment by jiangtao-zzz** [comment]
Hello, for example, when a slice fails to upload a large file, you need to try again。
This is my realization：[https://github.com/JiangTaoZzzz/async-pool/tree/dev-20210820/initiate-retry](url)

**Comment by rxaviers** [comment]
Closed in favor of https://github.com/rxaviers/async-pool/pull/26#issuecomment-902590892
