### ISSUE TITLE
Unhandled rejections in some corner case

### ISSUE THREAD

**Issue by gluck** [rxaviers/async-pool#32]
Because `executing` array can be left un-raced, even after #9 fix cases of unhandled exceptions can occur, e.g.:

```
> asyncPool = require('tiny-async-pool')
> await asyncPool(2, [0,1,2], (i,a) => i<a.length-1 ? Promise.resolve(i) : Promise.reject(i)).catch(()=>{/*ignore*/})
undefined
> Uncaught 2 <-- shouldn't be logged as we catch exceptions
```

**Comment by rxaviers** [comment]
Thank you for reporting this issue.

**Comment by gluck** [comment]
Was spotted in https://github.com/vitejs/vite/pull/4120 where @ArnaudBarre did a fix, if you want to port it:
https://github.com/vitejs/vite/pull/4120/files#diff-071a32aedd2ea59472ebb69fb456e818b103d1a332da632e12c2d54395938ad1R684
