### ISSUE TITLE
Adding dynamically new tak in the pool

### ISSUE THREAD

**Issue by fvisticot** [rxaviers/async-pool#8]
Is it possible to "dynamically" add new task in the pool ?
1. Init pool with concurrency
2. Add / Stream async task in the pool

**Comment by rxaviers** [comment]
Yeap, I believe you can. If `array` is the variable you pass to `asyncPool`, you may be able to `array.push` new stuff in there dynamically. Worth to check, but I believe you can. Feel free to post new comments and I can reopen if needed.
